language: python
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key: c6efefcf-08ef-4271-aa6f-757ba235d957
  app: encuesta-preinscripcion-bknd

install:
  - pip install -r requirements.txt

script:
  - pytest

cache:
  - pip
