#Docker compose version
version: '2.3'
services:
  encuesta-preinscripcion-backend_1:
    container_name: app-backend_1
    #Que siempre haga restart cuando falle. Comentar para q no se levante cada vez q se prende la maquina
    #restart: always
    #Que haga build en el directorio actual
    build: .
    #command: newrelic-admin run-program gunicorn -w 1 -b :8000 wsgi:app --error-logfile logs/error.log
    command: newrelic-admin run-program gunicorn -w 1 -b :8000 wsgi:app --error-logfile logs/error.log
    restart: always
    #Los puertos que va a usar
    #ports:
    #  - 8000:8000
    links:
      - db
    #  - nginx
    #El directorio que va a actualizar cuando vea cambios
    volumes:
      - .:/app
    cpus: '1'
    # 256 MB como maximo
    mem_limit: 512m
    environment:
      NEW_RELIC_CONFIG_FILE: /app/newrelic.ini

  db:
    container_name: postgres
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: encuestas

  nginx:
    container_name: nginx-container
    restart: always
    build: ./nginx
    ports:
      - "5000:80"
    depends_on:
      - encuesta-preinscripcion-backend_1

  memcached:
    container_name: memcached
    image: memcached:1.5-alpine
    ports:
      #Me conecto a traves de memcached:11211
      - 11211:11211
