"""empty message

Revision ID: 060102096fce
Revises: 0cfa50a9a7a4
Create Date: 2017-12-09 10:03:29.036880

"""

# revision identifiers, used by Alembic.
revision = '060102096fce'
down_revision = '0cfa50a9a7a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encuestas', sa.Column('respondida', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encuestas', 'respondida')
    # ### end Alembic commands ###
