"""empty message

Revision ID: 2c6af27fcd79
Revises: cee00397dd47
Create Date: 2017-12-04 17:25:38.349854

"""

# revision identifiers, used by Alembic.
revision = '2c6af27fcd79'
down_revision = 'cee00397dd47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preinscripcion',
    sa.Column('comision_id', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comision_id'], ['comisiones.id'], ),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id'], ),
    sa.PrimaryKeyConstraint('comision_id', 'encuesta_id')
    )
    op.add_column('cursables', sa.Column('materia_id', sa.Integer(), nullable=False))
    op.drop_constraint('cursables_comision_id_fkey', 'cursables', type_='foreignkey')
    op.create_foreign_key(None, 'cursables', 'materias', ['materia_id'], ['id'])
    op.drop_column('cursables', 'comision_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursables', sa.Column('comision_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cursables', type_='foreignkey')
    op.create_foreign_key('cursables_comision_id_fkey', 'cursables', 'comisiones', ['comision_id'], ['id'])
    op.drop_column('cursables', 'materia_id')
    op.drop_table('preinscripcion')
    # ### end Alembic commands ###
