"""empty message

Revision ID: 55d856a853d6
Revises: 060102096fce
Create Date: 2017-12-09 10:22:01.323549

"""

# revision identifiers, used by Alembic.
revision = '55d856a853d6'
down_revision = '060102096fce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encuestas', sa.Column('modificable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encuestas', 'modificable')
    # ### end Alembic commands ###
