"""empty message

Revision ID: 777a50520c42
Revises: None
Create Date: 2017-12-08 12:38:39.498629

"""

# revision identifiers, used by Alembic.
revision = '777a50520c42'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('cuatrimestre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiaresponses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aprobadas',
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('materia_id', 'encuesta_id')
    )
    op.create_table('cursables',
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('materia_id', 'encuesta_id')
    )
    op.create_table('preinscripcion',
    sa.Column('comision_id', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comision_id'], ['comisiones.id'], ),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id'], ),
    sa.PrimaryKeyConstraint('comision_id', 'encuesta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preinscripcion')
    op.drop_table('cursables')
    op.drop_table('aprobadas')
    op.drop_table('materiaresponses')
    op.drop_table('encuestas')
    op.drop_table('comisiones')
    op.drop_table('usuarios')
    op.drop_table('ofertas')
    op.drop_table('materias')
    # ### end Alembic commands ###
