"""empty message

Revision ID: 7bb23bc71905
Revises: d84a3886b6a1
Create Date: 2017-12-08 13:52:34.782793

"""

# revision identifiers, used by Alembic.
revision = '7bb23bc71905'
down_revision = 'd84a3886b6a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_authenticated')
    # ### end Alembic commands ###
