"""empty message

Revision ID: 9c28300c89db
Revises: 468733527910
Create Date: 2017-12-10 09:08:06.435755

"""

# revision identifiers, used by Alembic.
revision = '9c28300c89db'
down_revision = '468733527910'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imposibilitadas',
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('materia_id', 'encuesta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imposibilitadas')
    # ### end Alembic commands ###
