"""empty message

Revision ID: cee00397dd47
Revises: e636fc25a5cf
Create Date: 2017-11-27 12:13:52.926345

"""

# revision identifiers, used by Alembic.
revision = 'cee00397dd47'
down_revision = 'e636fc25a5cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('encuestas', sa.Column('oferta_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'encuestas', 'ofertas', ['oferta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encuestas', type_='foreignkey')
    op.drop_column('encuestas', 'oferta_id')
    op.drop_table('ofertas')
    # ### end Alembic commands ###
