"""empty message

Revision ID: d59bb3f57c52
Revises: 7bb23bc71905
Create Date: 2017-12-08 14:08:09.273434

"""

# revision identifiers, used by Alembic.
revision = 'd59bb3f57c52'
down_revision = '7bb23bc71905'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_active')
    op.drop_column('usuarios', 'is_authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
