"""empty message

Revision ID: e636fc25a5cf
Revises: None
Create Date: 2017-11-27 11:45:22.889825

"""

# revision identifiers, used by Alembic.
revision = 'e636fc25a5cf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('cuatrimestre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aprobadas',
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('materia_id', 'encuesta_id')
    )
    op.create_table('cursables',
    sa.Column('comision_id', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comision_id'], ['comisiones.id'], ),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id'], ),
    sa.PrimaryKeyConstraint('comision_id', 'encuesta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cursables')
    op.drop_table('aprobadas')
    op.drop_table('encuestas')
    op.drop_table('comisiones')
    op.drop_table('materias')
    op.drop_table('alumnos')
    # ### end Alembic commands ###
